name: AWS SAM Python
run-name: AWS ${{ github.head_ref }}
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  id-token: write
jobs:
  aws_sam:
    name: AWS SAM
    uses: fabrinator/actions/.github/workflows/aws-sam.yaml@feature/oidc-auth
    with:
      PYTHON_VERSION: 3.10.14
      PROJECT_FOLDER: aws-route-53-automation-relay
      AWS_ACCOUNT: 912008965710
    secrets: inherit